# -*- coding: utf-8 -*-
"""feature_extraction_body_language.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VQcIApYvECcYUyNB1ahX7mxSLMIqDtRZ
"""

# importing and modifying version of necessary libraries
!pip install mediapipe opencv-python pandas scikit-learn keras tensorflow tflite
!pip install numpy>=1.26,<=2 --force-reinstall
!pip install scikit-learn --upgrade --force-reinstall
!pip install scipy --upgrade --force-reinstall



#!pip install mediapipe opencv-python pandas scikit-learn keras tensorflow tflite


#!pip uninstall scikit-learn -y
#!pip install scikit-learn
#!pip install scikit-learn==1.3.2
#!pip install numpy --upgrade  # Upgrade NumPy
#!pip install scipy --upgrade  # Upgrade or reinstall SciPy

import sklearn
sklearn.__version__


import mediapipe as mp
import cv2

mp_drawing = mp.solutions.drawing_utils # Drawing helpers
mp_holistic = mp.solutions.holistic # Mediapipe Solutions

#import the model of body languagendetection
import pickle

# Attempt to load the model and handle the potential error
try:
    with open("body_language.pkl", 'rb') as f:
        model = pickle.load(f)
        print("Model loaded successfully.")
except ValueError as e:
    print("Error loading model:", e)
    print("Check scikit-learn version compatibility or try recreating the model.")

import numpy as np
import pandas as pd
from google.colab.patches import cv2_imshow

# function that finds the avrage confidence levels
def make_predictions(frame):

  with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    body_language_class = None
    body_language_prob = None
    # Recolor Feed
    image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    image.flags.writeable = False


    # Make Detections
    results = holistic.process(image)


    # Recolor image back to BGR for rendering
    image.flags.writeable = True
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    #cv2_imshow(image)


    # 1. Draw face landmarks
    mp_drawing.draw_landmarks(image, results.face_landmarks, mp_holistic.FACEMESH_CONTOURS,
                            mp_drawing.DrawingSpec(color=(80,110,10), thickness=1, circle_radius=1),
                            mp_drawing.DrawingSpec(color=(80,256,121), thickness=1, circle_radius=1)
                            )

    # 2. Right hand
    mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS,
                            mp_drawing.DrawingSpec(color=(80,22,10), thickness=2, circle_radius=4),
                            mp_drawing.DrawingSpec(color=(80,44,121), thickness=2, circle_radius=2)
                            )

    # 3. Left Hand
    mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS,
                            mp_drawing.DrawingSpec(color=(121,22,76), thickness=2, circle_radius=4),
                            mp_drawing.DrawingSpec(color=(121,44,250), thickness=2, circle_radius=2)
                            )

    # 4. Pose Detections
    mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS,
                            mp_drawing.DrawingSpec(color=(245,117,66), thickness=2, circle_radius=4),
                            mp_drawing.DrawingSpec(color=(245,66,230), thickness=2, circle_radius=2)
                            )
    # Export coordinates
    try:
      # Extract Pose landmarks
      pose = results.pose_landmarks.landmark
      pose_row = list(np.array([[landmark.x, landmark.y, landmark.z, landmark.visibility] for landmark in pose]).flatten())

      # Extract Face landmarks
      face = results.face_landmarks.landmark
      face_row = list(np.array([[landmark.x, landmark.y, landmark.z, landmark.visibility] for landmark in face]).flatten())

      # Concate rows
      row = pose_row+face_row

      # Make Detections
      X = pd.DataFrame([row])
      body_language_class = model.predict(X)[0]
      predicted_classes = model.predict(X)
      body_language_prob = model.predict_proba(X)[0]


      # Grab ear coords
      coords = tuple(np.multiply(
                      np.array(
                          (results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_EAR].x,
                            results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_EAR].y))
                  , [640,480]).astype(int))

      cv2.rectangle(image,
                    (coords[0], coords[1]+5),
                    (coords[0]+len(body_language_class)*20, coords[1]-30),
                    (245, 117, 16), -1)
      cv2.putText(image, body_language_class, coords,
                  cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)

      # Get status box
      cv2.rectangle(image, (0,0), (250, 60), (245, 117, 16), -1)

      # Display Class
      cv2.putText(image, 'CLASS'
                  , (95,12), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 1, cv2.LINE_AA)
      cv2.putText(image, body_language_class.split(' ')[0]
                  , (90,40), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)

      # Display Probability
      cv2.putText(image, 'PROB'
                  , (15,12), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 1, cv2.LINE_AA)
      cv2.putText(image, str(round(body_language_prob[np.argmax(body_language_prob)],2))
                  , (10,40), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)


    except:
      pass
    #print([body_language_class, body_language_prob])
    if body_language_class == None:
      return 0
    else:
      return body_language_prob[np.argmax(body_language_prob)]

import numpy as np
import cv2
import matplotlib.pyplot as plt

# Initialize video capture
def divideFramesAndCutHalfAndCalc(path):
  vidcap = cv2.VideoCapture(path)
  success, image = vidcap.read()
  fps = vidcap.get(cv2.CAP_PROP_FPS)
  count = 0

  # Get frame dimensions
  frame_height, frame_width = image.shape[:2]
  sum=0.0
  numOfDetetedFaces=0
  precentEveryXsec=[]
  X=10
  while success:
      # Crop the frame to the left half
      left_half = image[:, :frame_width // 2]

      # Convert the cropped frame to RGB
      left_half_rgb = cv2.cvtColor(left_half, cv2.COLOR_BGR2RGB)

      # Append the processed frame to the array

      if count>=151 and count<=3752:
        acc = make_predictions(left_half_rgb)
        if(acc!=0):
          numOfDetetedFaces=numOfDetetedFaces+1
        sum=sum+acc
        if count!=151 and (count-151)%(X*int(fps))==0:
          if (numOfDetetedFaces!=0):
            precentEveryXsec.append(sum/numOfDetetedFaces)
          else:
            precentEveryXsec.append(0)
          numOfDetetedFaces=0
          sum=0.0
      # Save the frame (optional)
      #cv2.imwrite(f"frame{count}.jpg", left_half)

      # Read the next frame
      success, image = vidcap.read()
      count += 1
      if count%100==0:
        print('Read a new frame: ', success, count)
        plt.imshow(left_half_rgb)
        plt.show()

  # Release the video capture object
  vidcap.release()



  return precentEveryXsec

#manual upload and running of the videos due to university policy
print(divideFramesAndCutHalfAndCalc("/content/A1A1.mp4"))
