# -*- coding: utf-8 -*-
"""feature_extraction_facial_expression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oXH_mRL3L9gi7_G-2A_JfaTq-KXwAC3i
"""

#import necessary libraries
!pip install fer
import matplotlib.pyplot as plt
from fer import FER
import cv2
import numpy as np


#emotion prediction function
# input = image
# output = maximal confidence value (of the highest ranking emotion)
def predictUsingFer(img):
  detector = FER()
  arr = detector.detect_emotions(img)
  print(arr)
  max=0.0 #confidence value
  if arr:  # Check if any faces were detected
    emotions = arr[0]['emotions']
    if emotions['angry']>max:
        max = emotions['angry']
    if emotions['disgust']>max:
        max = emotions['disgust']
    if emotions['fear']>max:
        max = emotions['fear']
    if emotions['happy']>max:
        max = emotions['happy']
    if emotions['sad']>max:
        max = emotions['sad']
    if emotions['surprise']>max:
        max = emotions['surprise']
  else:
    print("No faces detected in the image.")
    plt.imshow(img)
    plt.show()
    return 0
  return max


# Initialize video capture
# input: path to load video file
# output: array of confidence for the video
def divideFramesAndCutHalf(path):
  vidcap = cv2.VideoCapture(path)
  success, image = vidcap.read()
  fps = vidcap.get(cv2.CAP_PROP_FPS)
  count = 0
  sum=0.0
  numOfDetetedFaces=0
  percenteveryXsec=[]
  X=10
  # Get frame dimensions
  frame_height, frame_width = image.shape[:2]

  while success:
      # Crop the frame to the left half
      left_half = image[:, :frame_width // 2]

      # Convert the cropped frame to RGB
      left_half_rgb = cv2.cvtColor(left_half, cv2.COLOR_BGR2RGB)

      acc=predictUsingFer(left_half_rgb)
      if(acc!=0):
        numOfDetetedFaces=numOfDetetedFaces+1
      sum=sum+acc
      if (count-151)!=0 and (count-151)%(X*int(fps))==0:
        if (numOfDetetedFaces!=0):
          percenteveryXsec.append(sum/numOfDetetedFaces)
        else:
          percenteveryXsec.append(0)
        numOfDetetedFaces=0
        sum=0
      success, image = vidcap.read()
      count += 1
      print('Read a new frame: ', success)

  # Release the video capture object
  vidcap.release()

  return percenteveryXsec

#manual upload and running of the videos due to university policy
path = "/content/vidName.mp4"
print(divideFramesAndCutHalf(path))