# -*- coding: utf-8 -*-
"""feature_extraction_audio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LxWi9utYh1Hozp9ciCt10feB61kXAQp_
"""

#import necessary libraries


!pip install pydub numpy
!pip install moviepy
!pip install librosa pyloudnorm
from moviepy.editor import VideoFileClip

def convert_mp4_to_mp3(input_file_path, output_file_path):
    # Load the video clip
    video_clip = VideoFileClip(input_file_path)

    # Extract audio from the video
    audio_clip = video_clip.audio

    # Write the audio to an mp3 file
    audio_clip.write_audiofile(output_file_path)

# Example usage
input_file_path = 'path'
output_file_path = 'pathAudio.mp3'

convert_mp4_to_mp3(input_file_path, output_file_path)

from math import sqrt
from pydub import AudioSegment
import numpy as np

#calculate volume levels
# input: path of mp3
# output: array of the avrage volume levels
def calculate_volume_levels(file_path):
    # Load the audio file
    audio = AudioSegment.from_mp3(file_path)

    # Initialize an empty list to store average volume levels
    volume_levels = []

    # Calculate the number of 10-second segments
    startIndex=5000
    num_segments = (len(audio) -startIndex)// 10000 + (len(audio) % 10000 > 0)

    # Iterate over each segment
    for i in range(num_segments):
        start_time = i * 10000+startIndex
        end_time = min((i+1) * 10000, len(audio))+startIndex

        # Extract a 10-second segment
        segment = audio[start_time:end_time]

        # Convert the segment to mono and normalize volume
        segment_mono = segment.set_channels(1).normalize()

        # Check if the segment is empty
        # Export the segment to an array
        samples = np.array(segment_mono.get_array_of_samples())
        # Calculate the root mean square (RMS) of the segment
        for t in range(len(samples)):
          samples[t] = np.abs(samples[t]*samples[t])
        x = np.mean(samples)
        print(x)
        rms = sqrt(x)

        # Append the RMS value to the list
        volume_levels.append(rms)

    return volume_levels

# Example usage
file_path = output_file_path
volume_levels = calculate_volume_levels(file_path)
print("Volume levels over 10-second intervals:", volume_levels)

#modifying array length
volume_levels_twoMin = []
for i in range (12):
  volume_levels_twoMin.append(volume_levels[i])
print(volume_levels_twoMin)